### PR TITLE
update to rn 25.1 and more

### PR DESCRIPTION
**Pull request by FaridSafi**

### CODE REVIEW

**Comment by FaridSafi** [comment]
Hi @jlyman, it is possible to reach you via twitter ? I would like to ask you questions about potential improvements like tab bar, multiple navigation state, etc.

**Comment by jlyman** [comment]
@FaridSafi sure thing, on Twitter at @jlyman. Thanks for the PR! Just got back from some time off, I'll review it ASAP.

**Comment by jlyman** [comment]
I'd love to get the community's thoughts on a point related to this PR, and @FaridSafi definitely chime in on them as well.

**I'm not sure about the default inclusion of the Redux devtools here, as well as the linting packages.** The objective of this repo is to be a very concise and approachable, and to be a learning tool above all else. I don't want it to morph into a base from which to build a real app on, or a boilerplate or starter kit in any way. 

In a real application, using linting libs and devtools would be a definite must, and I'd be all over it. But here I think the focus really should just be on the _how_ around connecting a Redux-like architecture to NavigationExperimental. As such I think I'd vote to not include these by default in the repo.

Thoughts?

**Comment by jlyman** [comment]
@FaridSafi going to go ahead and close this since we updated to 0.25.1. If we want to have a discussion about devtools and linting lets open a separate issue for it.

**Pull request closed without merging**
